# Generated by Django 5.2.5 on 2025-09-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('manager', 'Manager'), ('family', 'Family')], max_length=20)),
                ('is_featured', models.BooleanField()),
            ],
        ),
    ]
