# Generated by Django 5.2.5 on 2025-09-13 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('jersey', 'Jersey'), ('shorts', 'Shorts'), ('jacket', 'Jacket'), ('accessory', 'Accessory'), ('ball', 'Ball'), ('exclusive', 'Exclusive')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('bonus_points', models.IntegerField(default=0)),
                ('brand', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
    ]
