# Generated by Django 5.2.5 on 2025-09-13 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('jersey', 'Jersey'), ('shorts', 'Shorts'), ('jacket', 'Jacket'), ('accessory', 'Accessory'), ('ball', 'Ball'), ('exclusive', 'Exclusive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
