# Generated by Django 5.2.5 on 2025-09-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unisex', 'Unisex')], default='Unisex', max_length=20),
        ),
    ]
