# Generated by Django 5.2.5 on 2025-09-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
